Bau add template yaml
govuk-one-login/ipv-cri-kbv-hmrc-front pull request #15
Opened 2023-11-24 10:06 UTC by surajkumar

## Proposed changes

Added a `template.yaml` for deploying the KBV HMRC Front repo. This was missing.

2023-11-24 13:57 UTC, CharlesIC requested changes

2023-11-24 13:57 UTC, CharlesIC commented on .github/workflows/post-merge-to-dev.yml
> +      - bau-add-template-yaml
```suggestion
```
This needs to be removed

2023-11-24 13:59 UTC, CharlesIC commented on deploy/template.yaml
> +    Value: !Sub "${AWS::StackName}"
Why is the stack name being output here? 
In order to access outputs from a stack, one needs to know the stack name first.... So accessing an output which is the stack name would never be useful and is not needed.

I've seen this in a lot of templates and I assume this one was copied from somwewhere else, but this should be removed.
```suggestion
  StackName:
```

2023-11-27 11:51 UTC, mrdoodles approved these changes

2023-11-27 12:09 UTC, CharlesIC approved these changes

2023-11-27 12:10 UTC, merged