PYIC-5212: add welesh translation for payslip NI page
govuk-one-login/ipv-cri-kbv-hmrc-front pull request #82
Opened 2024-03-01 14:21 UTC by shivanshuit914

## Proposed changes

- Add welesh translation for payslip NI page
- Fix page title

### What changed

- Welsh translation yml files.
- Fixed page title in view using correct property.

### Why did it change

- To support welsh translation.

### Issue tracking

- [PYIC-5212](https://govukverify.atlassian.net/browse/PYIC-5212)
<img width="699" alt="Screenshot 2024-03-05 at 11 12 33" src="https://github.com/govuk-one-login/ipv-cri-kbv-hmrc-front/assets/3963744/38e0e21f-3064-432f-9a24-8f7f520bf926">

[PYIC-5212]: https://govukverify.atlassian.net/browse/PYIC-5212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-01 15:06 UTC, DanCorderIPV submitted a review, later dismissed

2024-03-01 15:39 UTC, blakeyp commented on src/locales/cy/pages.yml
> +  inset: Defnyddiwch slip cyflog wedi'i ddyddio ar ôl {{ threeMonthsAgo }} i ateb y cwestiwn hwn
We'll need to make sure the date (month) gets translated too - we should handle that in [PYIC-5211](https://govukverify.atlassian.net/browse/PYIC-5211)

2024-03-01 15:45 UTC, blakeyp commented on src/locales/cy/pages.yml
> +  abandon: "<a href='/kbv/abandon' class='govuk-link' data-id='abandon'>Mae angen i mi brofi fy hunaniaeth mewn ffordd arall</a>"
`abandon` will be shared across several pages, could we pull it out of this page and put it under a `shared` key or something

2024-03-01 15:48 UTC, blakeyp commented on src/views/kbv/single-amount-question.njk
>    <h1 class="govuk-heading-l"> {{ translate("pages.rti-payslip-national-insurance.title") }} </h1>
As this template will be shared across multiple questions, we'll need a way of passing in the question key for the translations, maybe using `presenters` to build the content instead

2024-03-05 14:21 UTC, blakeyp commented on src/app/kbv/controllers/single-amount-question.js
> +        locals.threeMonthsAgo = moment()
Maybe `locals.dynamicDate` given the 3 months comes from the backend? (and the template doesn't care about this context)

2024-03-05 14:21 UTC, blakeyp commented on src/app/kbv/controllers/single-amount-question.js
> +        prefix: req.session.question?.info?.prefix || " ",
Is this used?

2024-03-05 14:21 UTC, blakeyp commented on src/views/kbv/single-amount-question.njk
> +{% set hmpoTitle = translate("pages.rti-payslip-national-insurance.title") %}
should be `question.title` ?

2024-03-05 14:21 UTC, blakeyp commented on src/app/kbv/controllers/single-amount-question.js
> +          .format("DD MMMM YYYY");
We could abstract this part to a presenter, then we can test it in isolation (including test for welsh) and stub it in the controller tests?

2024-03-05 16:31 UTC, blakeyp commented on src/locales/cy/pages.yml
> +  title: Rhowch swm yr Yswiriant Gwladol a dalwyd gennych o slip cyflog diweddar
We may need to add a separate title and h1 here, just awaiting confirmation from UCD

2024-03-06 10:55 UTC, blakeyp commented on src/locales/cy/pages.yml
> +  title: Rhowch swm yr Yswiriant Gwladol a dalwyd gennych o slip cyflog diweddar
Had confirmation we don't need to (title and h1 are the same)

2024-03-06 13:24 UTC, blakeyp approved these changes

2024-03-07 10:02 UTC, merlinc requested changes
Could we get better commit hygiene as per [GDS Way](https://gds-way.digital.cabinet-office.gov.uk/standards/source-code/working-with-git.html#commits)

Many of these commits are doing multiple things, and fixup commits (such as "fix linting") should be included into the other changes that you have done.

2024-03-08 10:27 UTC, blakeyp approved these changes

2024-03-08 10:28 UTC, merged