PYIC-5211: use dynamic month for the inset texts
govuk-one-login/ipv-cri-kbv-hmrc-front pull request #93
Opened 2024-03-06 15:52 UTC by shivanshuit914

## Proposed changes

### What changed

- use dynamic month for the inset texts

### Why did it change

- To pass month dynamically to inset text

### Issue tracking

- [PYIC-5211](https://govukverify.atlassian.net/browse/PYIC-5211)

[PYIC-5211]: https://govukverify.atlassian.net/browse/PYIC-5211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-07 09:44 UTC, merlinc requested changes
I know this is a WIP draft, when this PR is ready, I'd like to see there be specifically coded `it` tests for the various permutations of working with the additional `months` data

2024-03-11 15:10 UTC, blakeyp commented on tests/unit/src/presenters/question-to-inset.test.js
> +        months: 3,
In `questions.json` which mocks up what we'll get from the API, the months value is a string

2024-03-11 15:13 UTC, blakeyp commented on tests/unit/src/presenters/question-to-inset.test.js
> +  it("should call translate using questionID without month when month is 0", () => {
`when month is undefined` ? (we won't expect it to be provided at all if not needed)

2024-03-11 15:16 UTC, blakeyp commented on tests/unit/src/presenters/question-to-inset.test.js
> +  it("should call translate using questionID and months", () => {
I don't think we need this case, it's covered by the others

2024-03-12 15:50 UTC, blakeyp commented on src/locales/cy/pages.yml
> +  abandon: "<a href='/kbv/abandon' class='govuk-link' data-id='abandon'>Rwyf angen profi fy hunaniaeth mewn ffordd arall</a>"
Will confirm with UCD and we can update this back later

2024-03-12 16:04 UTC, blakeyp commented on tests/unit/src/presenters/question-to-inset.test.js
> +  it("should retrun empty string when translation not present", () => {
typo *return

2024-03-12 16:07 UTC, blakeyp commented on tests/unit/src/presenters/question-to-inset.test.js
> +  const englishDate = "01 February 2024";
UCD will want it in the form `1 February 2024` (no leading 0s) so I think the moment format will need updating to `D MMMM YYYY` ?

2024-03-12 16:29 UTC, blakeyp approved these changes

2024-03-13 13:55 UTC, merlinc approved these changes

2024-03-13 13:58 UTC, merged